image: sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.9.4_2.13.11

stages:
  - format-check
  - compile

format-check:
  stage: format-check
  script:
    - sbt scalafmtCheckAll

compile:
  stage: compile
  script:
    - sbt compile
