version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: employee_access_control_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql

volumes:
  postgres_data: {}

